//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaMedica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string usuario_alta { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public int estado { get; set; }
        public int tipo_usuario { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual tipos_usuarios tipos_usuarios { get; set; }
    }
}
